/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>
void delay1();
void delay2();

void clear();
void function1();
void function2();
void function3();
void function4();
void function5();
void blue(int);
void red(int);
void orange(int);
void green(int);

int i,j,k,p;
uint32_t *p21=(uint32_t*)0X48001000;
uint32_t *p31=(uint32_t*)0X48001014;
uint32_t *p1=(uint32_t*)0X40021014;
uint32_t *p2=(uint32_t*)0X48001000;
uint32_t *inA= (uint32_t*)(0x48000010);

uint8_t change=0;

uint32_t *p3=(uint32_t*)0X48001014;
int main()
{
	*p1 |=(1<<21);
	*p1 |=(1<<17);

			 while (1)
			{
				 function1();
				 delay1();
				 function2();
				 delay1();
				 function3();
				 delay1();
				 function4();
				 delay1();
				 function5();
				 delay1();

			}

}
void clear()
{
	*p21 &=00000000;
	*p31 &=00000000;

}
void delay2()
{
	int i;
	for(i=500000;i>=0;i--);
}
void delay1()
{
	int i;
	for(i=1000000;i>=0;i--);
}
void blue(int i)
{
	if(i==1)
	{
		*p2 &=~(12<<16);
		*p2 |=(1<<16);
		*p3 |=(1<<8);
	}
	else
	{
		*p2 &=~(12<<24);
		*p2 |=(1<<24);
		*p3 |=(1<<12);
	}
}
void red(int i)
{
	if(i==1)
	{
		*p2 &=~(3<<18);
		*p2 |=(1<<18);
		*p3 |=(1<<9);
	}
	else
	{
		*p2 &=~(3<<26);
		*p2 |=(1<<26);
		*p3 |=(1<<13);
	}
}

void orange(int i)
{
	if(i==1)
	{
		*p2 &=~(12<<20);
		*p2 |=(1<<20);
		*p3 |=(1<<10);
	}
	else
	{
		*p2 &=~(12<<28);
		*p2 |=(1<<28);
		*p3 |=(1<<14);
	}
}
void green(int i)
{
	if(i==1)
	{
		*p2 &=~(3<<22);
		*p2 |=(1<<22);
		*p3 |=(1<<11);
	}
	else
	{
		*p2 &=~(3<<30);
		*p2 |=(1<<30);
		*p3 |=(1<<15);
	}
}
void function1()
{
		while(!(*inA & 0x1))
		{
			i=8,j=12;
			k=i*2;
			while((i>=8)&&(i<=15))
			{
				*p2 &=~(j<<k);
				*p2 |=(1<<k);
				*p3 |=(1<<i);
				++i;
				k=i*2;
				j=(j==12)?3:12;
				delay2();
				clear();
			}

		}
		change++;
}
void function2()
{
		while(!(*inA & 0x1))
		{
			i=8,j=12;
			k=i*2;
			while((i>=8)&&(i<=11))
			{
				*p2 &=~(j<<k);
				*p2 |=(1<<k);
				*p3 |=(1<<i);
				*p21 &=~(j<<(k+8));
				*p21 |=(1<<(k+8));
				*p31 |=(1<<(i+4));
				++i;
				k=i*2;
				j=(j==12)?3:12;
				delay2();
				clear();
			}

		}
		change++;
}
void function3()
{

	while(!(*inA & 0x1))
	{
		blue(1);
		delay2();
		red(1);
		delay2();
		orange(1);
		delay2();
		green(1);
		delay2();
		blue(2);
		delay2();
		red(2);
		delay2();
		orange(2);
		delay2();
		green(2);
		delay2();

	}
	change++;
}
void function4()
{
	while(!(*inA & 0x1))
	{
	blue(1);
	delay2();
	orange(1);
	delay2();
	blue(2);
	delay2();
	orange(2);
	delay2();
	clear();
	red(1);
	delay2();
	green(1);
	delay2();
	red(2);
	delay2();
	green(2);
	delay2();

	}
	change++;
}
void function5()
{
	while(!(*inA & 0x1))
	{
	blue(1);
	red(1);
	orange(1);
	green(1);
	blue(2);
	red(2);
	orange(2);
	green(2);
	delay2();
	clear();
	}
	change++;
}













